### ISSUE TITLE
Set up new database with Mongo Atlas

### ISSUE THREAD

**Issue by ahijaouy** [GTBitsOfGood/drawchange#168]
mLab was bought by MongoDB and they're going to be [shutting down in October of 2019](https://docs.mlab.com/mlab-to-atlas/). To get ahead of this, we want to move over to[ Mongo Atlas ](https://www.mongodb.com/cloud/atlas)(the new solution).

- [x] Create dev database on atlas
- [x] Create staging database on atlas
- [x] Set staging database connection URI on Heroku env vars.

**Comment by nareddyt** [comment]
- Dev database is setup on Atlas, connection string is in slack.
- Staging database is setup on Atlas, connection string is updating in Heroku.

Note that both databases are completely empty now. Please clear your cookies on localhost:3000, localhost:30001, and drawchange.herokuapp.com for the app to work properly.

Also send me an email address I can use to add you as an Admin on MongoDB Atlas!

**Comment by nareddyt** [comment]
> * [x]  Create staging database on atlas
> * [x]  Set staging database connection URI on Heroku env vars.

By the way, did you mean staging or prod? Will we be running prod in atlas as well?

**Comment by ahijaouy** [comment]
So we don't really have a _prod_ server running rn. Until we get v1.0 officially launched there won't be prod. What we have running on the heroku is more of a staging or uat (user acceptance testing) box where we are testing our code in a production like environment, but it's not really production ready yet. 

When we get closer to releasing v1.0 we can set up the prod db.
