### ISSUE TITLE
Email Integration for Volunteer Application Status

### ISSUE THREAD

**Issue by ahijaouy** [GTBitsOfGood/drawchange#169]
We want to incorporate email notifications for volunteers to track the status of their application. 

- [x] Write function `sendEmail(recipient, message)` that will send an email `message` to the `recipient` specified by the parameters. 
- [x] When a volunteer submits an application, they should get a confirmation email
- [x] When a volunteer's status changes to denied, they should get an email notification
- [x] When a volunteer's status changes to approved, they should get an email notification
- [x] Test with sendgrid

**Comment by nareddyt** [comment]
As discussed, we will rely on sending emails directly (instead of scheduling them asynchronously). For our workflows of sending emails when volunteer application status changes, this would be OK.
