### ISSUE TITLE
Update Backend Models to reflect new volunteer flow

### ISSUE THREAD

**Issue by ahijaouy** [GTBitsOfGood/drawchange#170]
New flow: User authenticates with Google, creates a User Profile (basic bio info), submits volunteer app. 

- [x] User Creds model created
- [x] User Creds REST endpoints created
- [x] User Data model created/update
- [x] User Data REST endpoints created/update
- [x] Temporarily comment out all Event related endpoints

Punted to #179 :
- [ ] User Creds tests written
- [ ] User Data tests written

**Comment by ahijaouy** [comment]
@nareddyt  can you confirm the status of the User Cred action items.

**Comment by nareddyt** [comment]
Just checked off the boxes above! 

Currently all user data is in a model called `User Data`. I imagine you want to break it up into `User Profile` and `Volunteer Application`, correct?

Are there any pros/cons of doing so?

**Comment by ahijaouy** [comment]
Hmmmmm, this was my initial reasoning because I was thinking that not every user (namely admins) would need to submit the volunteer app. Admins would just be instantly promoted to admin... 

But I realize that if we did it that way, we'd need a separate UI to display these people before they're promoted to admin.... so it seems it's simpler to just force everyone to fill out the application and then people can be promoted to admin from the volunteer list page. 

So in that case I don't see a reason to split it up!


Except maybe you consider that when the volunteer signs in we don't necessarily need all their application data to be sent to the frontend every time? The application data is only useful before they're approved? 

Idk it seems I'm talking myself out of uniting them now... What are your thoughts?

**Comment by nareddyt** [comment]
I think the performance gains of not sending back that data would be minimal. If we split that data, then we'd have to make two DB calls and "join" them to retrieve a single user's data.

I agree that it would be inconvenient for Admins to have to input all that info for no reason. Like you said, you'd have to change the frontend. Do you think you'd have time to do that before the deadline?

Perhaps we could make this a low-priority feature and work on it if we have time towards the end? Do you think admin UX would be acceptable if we keep the model the same for now?

**Comment by ahijaouy** [comment]
Updated UserData models/routes and frontend to be in sync.

**Comment by ahijaouy** [comment]
Moved all Testing requirements to #179
