### ISSUE TITLE
Admin Dash: Volunteer Filter 

### ISSUE THREAD

**Issue by RheaChatterjee** [GTBitsOfGood/drawchange#183]
**Is your feature request related to a problem? Please describe.**
We want admin to be able to filter approved volunteers. 

**Describe the solution you'd like**
We want a filter that takes in "volunteers" as props which is an array of user data. User data will eventually be pulled in from database. For now, user data will be a hard coded array based on backend-->src-->userData.js 

**Describe alternatives you've considered**

**Additional context**

**Comment by Holben888** [comment]
Created an issue for this that's a little clearer. Closing this one
