### ISSUE TITLE
Implement search by content 

### ISSUE THREAD

**Issue by Holben888** [GTBitsOfGood/drawchange#196]
Using the textbox, we should be able to search the content of each applicant document for specified text.

**Items to Research**
- [x] How search by text works in MongoDB. My understanding is you can index which fields should be searchable (look up Mongo's docs on indexing) and you can use the special "$text" key to find matching fields. 
- [x] The risk of a performance hit indexing too many things for search. If there is a problem, we should prioritize searching by history fields and address.

**Action Items**
- [x] Add necessary indexing to allow search by text in the database. This requires using the mongo shell in the terminal and connecting to the db.
- [x] Create an Express endpoint that
1. Accepts a search phrase as a param
2. Queries mongo with a try / catch block to search for that phrase on all fields indexed for searching
3. Returns a list of matching applicants in `userData`
- [x] Fire a call to the endpoint using axios whenever text is entered (or whenever a "submit" button is clicked to make the UI easier to implement). This query should be added to `AdminDash/queries.js` and be called from `AdminDash/ApplicantList.jsx`. 
- [x] Update the state in `AdminDash/index.js` with the users passed back from the API call.

**Items for the future**
- Global search is nice, but what is the applicants returned include some matches you didn't want to see? Like searching for a name and receiving some address matches? It would be nice to add a dropdown where the user can select which fields they want to search by.

**Comment by KanavKG** [comment]
All done.
