### ISSUE TITLE
Add to content search functionality

### ISSUE THREAD

**Issue by Holben888** [GTBitsOfGood/drawchange#199]
Content search is great, but what if it was **better?**

**Note**: layout will change once mockup is finished

**Action items**
- [x] Add a button to clear the current search and return to the list of all applicants. To best do this, the input should be reworked as follows:
1. Wrap the `<Input>` with a `<form>`. Make the header of this form 
`<form onSubmit={apiCallFunction()}>`. We're doing this to make our clear button easy to make. Also note that we don't need the `onKeyDown` anymore. A form just calls this function on enter by default!
2. Add a reactstrap button and set `type="reset"`. This will clear out the input box. You can just make the content the word "clear" until a delete icon gets added for you to use.
3. Do the necessary styling on the form so the layout looks correct. This is the tricky part. Look through the basics of how styled components work to see how you can make a form component with some styles. The only style you should need is `display: flex` and maybe some padding weirdness. If not, ask @Holben888 the CSS wizard ✨ 

more tasks to be added

**Comment by KanavKG** [comment]
All done :)
