### ISSUE TITLE
Add filter for year ranges

### ISSUE THREAD

**Issue by Holben888** [GTBitsOfGood/drawchange#201]
You should be able to filter applicants viewed by year, specifically the most recent 2-3 years.

**Action items**
- [x] Add a subsection and checkboxes to the filter modal for useful date ranges. Instead of basic "2019, 2018, 2017, etc.", I would suggest more adaptable labels. This is a good set of options: "past month, past 6 months, from 2019, from 2018, from 2017, 2016 and older."
- [x] Instead of hardcoding the year values, use the JavaScript `Date` object to get the current year and subtract years for each of the options. This can be set on the initial keys for the filter using a helper function. You can set key names dynamically using brackets (ex. `filters[Date.getFullYear()]: false`)
- [x] Now comes the tricky part: handling dates on the backend. Go to the "else" statement in `router.get('/')` of `users.js` to see all the current filter logic. Here, we want a special case for `req.query.date`. Grab that using an "if" statement and be sure to use a try / catch for in case the `JSON.parse` fails. This parsing will give you all the dates selected as keys of an object. You can get all these keys as an array by running `Object.keys(req.query.date)`. You can now iterate over these dates to make comparisons in Mongo.
- [ ] Use the greater than / less than operators to compare each date against the `createdAt` date on the user. Be sure to wrap the date string in `new Date(...)` so it's the right format for comparison. For example "from 2017" might look like:
`UserData.find({createdAt: {$gte: new Date(parseInt(year), 0), $lte: new Date(parseInt(year), 11)} })`

👆Breaking that down, `$gte` and `$lte` mean "greater than or equal to" and "less than or equal to", respectively. The `new Date` constructor takes the year, index of the month, and a bunch of other optional parameters. Here we just say the year and the first month of that year (0), then the same year and the last month (11).

- [ ] Instead of running a `UserData.find` for each date, add each as a key to the big "filter" object that gets thrown into a query at the end. This likely involves having the `createdAt` key, then a `{$or: ...}` that you would keep adding the greater than and less than comparisons too. This code will likely look pretty weird so Slack Ben-the-database-overload if it doesn't make sense. Also please note that `forEach(...)`, `map(...)`, and `reduce(...)` are awesome, so no for loops please!
- [ ] Test, test, test ✅

**Comment by KanavKG** [comment]
Added and tested! ✅
