### ISSUE TITLE
Search by content not sorted by date

### ISSUE THREAD

**Issue by Holben888** [GTBitsOfGood/drawchange#214]
**Describe the bug**
Any list of applicants from the database should be sorted most to least recent. The search by content endpoint forgets this in the query.

**To Reproduce**
Search for anything, then hit the "back" button. Note that the list of applicants is now in the wrong order.

**Action Items**
Take a look at the current `get('/')` endpoint in the backend's `users.js`. Look at how the `aggregate` function works. This should be duplicated in search by content, where we should run `aggregate` with the same sort by id `-1`, then the `$match` query. This should just be the same exact object we're currently passing into the `.find(...)` query.

**Comment by KanavKG** [comment]
All fixed!
