### ISSUE TITLE
Role Based Navbar Links

### ISSUE THREAD

**Issue by ahijaouy** [GTBitsOfGood/drawchange#51]
Currently unapproved volunteers and regular volunteers can see all the links on the navbar that should just be for admins. This should be fixed...

-> Unapproved Volunteers: Don't see anything except a logout and edit application.
-> Approved Volunteers: -> See My Profile link and their dashboard.

**Comment by krrishdholakia** [comment]
It’s a refresh issue. Once you refresh the page it changes the navbar.

Krrish

**Comment by ahijaouy** [comment]
Not having navbar reflect role specific information
