### ISSUE TITLE
Header mimics drawchange.org

### ISSUE THREAD

**Issue by zlillie** [GTBitsOfGood/drawchange#65]
Make the Header component mimic the navbar on the drawchange.org website. All the links should link back to the original drawchange.org website.

- [x]  About Us Dropdown
- [x] Contribute Dropdown
- [x] News Link
- [x] Activities Dropdown
- [x] Contact Link
- [x] Donate Link
- [x] Navbar is responsive

**Comment by ahijaouy** [comment]
Make the Header have the same links & styles as the drawchange.org header.

**Comment by thejameswang** [comment]
Responsiveness iffy, but basic functionality is done

**Comment by thejameswang** [comment]
Closed
