### ISSUE TITLE
Admin Dash: Volunteer Search Page

### ISSUE THREAD

**Issue by aballari9** [GTBitsOfGood/drawchange#68]
From the Admin Page we want to be able to search through all volunteers with the goal of applying filters to get a sub group of volunteers and being able to copy/paste their emails so admin can send them email. 

- [ ]  Table of all approved volunteers
- [ ] Be able to filter volunteers
- [ ] Get email addresses of volunteer subgroup

**Comment by Holben888** [comment]
This issue is now out of date based on the current dashboard concept. Closing for now
