### ISSUE TITLE
Change paragraph questions on registration

### ISSUE THREAD

**Issue by karachtani** [GTBitsOfGood/drawchange#69]
The paragraph questions (why drawchange etc.) can feel daunting. Make them less daunting.

**Comment by rcobelli** [comment]
Questions are

- Why are you interested in volunteering with drawchange?
- What would you need FROM us to support your timely completion of tasks? What supports your productivity? What sorts of recognition do you most value?
- What do you do when you realize you cannot keep a commitment?

**Comment by ArnabDey** [comment]
Not needed anymore
