### ISSUE TITLE
Volunteer Dashboard has info from drawchange.org volunteer portal

### ISSUE THREAD

**Issue by bharatsrirangam** [GTBitsOfGood/drawchange#70]
We want to duplicate the drawchange.org/volunteerportal as our Volunteer Dashboard for now. Eventually this should be updated in 2.0 release, but for 1.0 it's good.

- [x] Include Photo Gallery
- [x] Include text info from blue block

**Comment by ahijaouy** [comment]
TODO: Make Volunteer Dashboard display same information as the drawchange volunteer portal
