### ISSUE TITLE
Have pictures of children on their website/facebook/instagram on the vol. Portal 

### ISSUE THREAD

**Issue by bharatsrirangam** [GTBitsOfGood/drawchange#79]
On the Splash Screen and Volunteer Dashboard we want a photo gallery.

- [x] Photo gallery on Splash screen
- [x] Photo gallery on Volunteer Dashboard
- [x] Both photo galleries should be responsive

**Comment by ahijaouy** [comment]
TODO: Picture Gallery on Splash screen and volunteer dashboard.

**Comment by thejameswang** [comment]
When given more pictures, I will add 2 rows to make it look better. Limiting to 1 row to keep responsiveness, good. Could add Horizontal scroll.
